#!/usr/bin/bash

check_device_unused() {
    processes=$(fuser -v /dev/nvidia* 2>&1) # returns 0 if any file is in use, nonzero if no files are in use
    case $? in
        0)
            echo "dGPU is still in use, processes are: "
            echo "$processes"
            false
        ;;
        *)
            #echo "dGPU is not used"
            true
        ;;
    esac
}

unload_audio() {
    echo "0000:01:00.1" > /sys/bus/pci/drivers/snd_hda_intel/unbind
}

disable_gpu_acpi() {
    echo '\_SB.PCI0.PEG0.PEGP._OFF' > /proc/acpi/call 2> /dev/null
    result=$(tr -d '\0' < /proc/acpi/call)
    case $result in
        Error*)
            echo "dGPU disable ACPI call failed"
	    false
        ;;
        *)
            #echo "dGPU disable ACPI call succeeded"
	    true
        ;;
    esac
}

unload_nvidia_modules() {
    for m in nvidia_uvm nvidia_drm nvidia_modeset nvidia; do
        counter=0
        while [[ $counter -lt 10 ]]; do
            if modprobe -r $m; then
                #echo "module $m unloaded"
                continue 2
            fi
            counter=$counter+1
            sleep 1
        done
        echo "ERROR: unloading module $m failed"
        break
    done
}

remove_nvidia_pci_devices() {
    pci_ids=$(lspci -D | grep 'NVIDIA' | awk '{print $1}')
    for pci_id in $pci_ids; do
        echo 1 > "/sys/bus/pci/devices/${pci_id}/remove"
        pci_device_available=$(lspci -D | grep "${pci_id}")
        if [[ -n "$pci_device_available" ]]; then
            echo "Failed to remove PCI device ${pci_id}. Exiting..." >&2
            exit 1
        fi
    done
}

check_device_unused && unload_audio && unload_nvidia_modules && remove_nvidia_pci_devices
