---

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ sudoers_packages }}"
    state: "present"
  become: true

- name: "Create sudoers.d files"
  ansible.builtin.copy:
    dest: "{{ sudoers_config_path }}/{{ item.name }}"
    content: "{{ item.content }}"
    owner: "root"
    group: "root"
    mode: "0440"
  become: true
  loop: "{{ sudoers_config_files }}"

