---

- name: "Linux Setup"
  hosts: all
  
  tasks:
    - name: "Execute role"
      ansible.builtin.include_role:
        role: "{{ _role }}"
      when: "'role_' ~ _role in group_names"
      loop:
        - "system"
        - "mkinitcpio"
        - "systemd_boot"
        - "grub"
        - "systemd_resolved"
        - "networkmanager"
        - "user"
        - "sudoers"
        - "configfiles"
        - "packages"
        - "flatpak"
        - "aur"
        - "bluetooth"
        - "lact"
        - "sddm"

        - "neovim"
        - "keepassxc"
        - "discord"
        - "sunshine"

        # - "tuxedo_control_center"
        # - "nvidia"
        # - "thermald"
        # - "intel_undervolt"
        # - "ite8291"
      loop_control:
        loop_var: _role
