---

- name: "Update packages"
  ansible.builtin.package:
    upgrade: true
  become: true
  register: reg_packages_update

- name: "Print updated packages"
  ansible.builtin.debug:
    var: "reg_packages_update.packages"
  when: "reg_packages_update.changed is true"

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ packages_install }}"
    state: "present"
  become: true
  when: 
    - "packages_install is defined"
    - "packages_install is iterable and packages_install is not string"

- name: "Update flatpaks"
  ansible.builtin.command: 
    cmd: "flatpak update --noninteractive"
  register: reg_flatpak_update
  changed_when: "'app/' in reg_flatpak_update.stdout"
