---

all:
  hosts:
    daniel-fusion15:
    daniel-pc:

  children:
    group_brave:
      hosts:
        daniel-fusion15:
        daniel-pc:

    group_fonts:
      hosts:
        daniel-pc:

    group_gaming:
      hosts:
        daniel-pc:

    group_gui:
      children:
        group_plasma:

    group_logseq:
      hosts:
        daniel-fusion15:
        daniel-pc:

    group_plasma:
      hosts:
        daniel-pc:

    group_thunderbird:
      hosts:
        daniel-fusion15:
        daniel-pc:

    role_aur:
      hosts:
        daniel-pc:

    role_bluetooth:
      hosts:
        daniel-pc:

    role_configfiles:
      hosts:
        daniel-fusion15:
        daniel-pc:

    role_discord:
      hosts:
        daniel-fusion15:
        daniel-pc:

    role_flatpak:
      hosts:
        daniel-pc:

    role_grub:
      hosts:
        daniel-fusion15:

    role_intel_undervolt:
      hosts:
        daniel-fusion15:

    role_ite8291:
      hosts:
        daniel-fusion15:

    role_keepassxc:
      hosts:
        daniel-fusion15:
        daniel-pc:

    role_lact:
      hosts:
        daniel-pc:

    role_mkinitcpio:
      hosts:
        daniel-fusion15:
        daniel-pc:

    role_neovim:
      hosts:
        daniel-fusion15:
        daniel-pc:

    role_networkmanager:
      hosts:
        daniel-pc:

    role_nvidia:
      hosts:
        daniel-fusion15:

    role_packages:
      hosts:
        daniel-fusion15:
        daniel-pc:

    role_sddm:
      hosts:
        daniel-fusion15:
        daniel-pc:

    role_sudoers:
      hosts:
        daniel-pc:

    role_sunshine:
      hosts:
        daniel-pc:

    role_system:
      hosts:
        daniel-fusion15:
        daniel-pc:

    role_systemd_boot:
      hosts:
        daniel-pc:

    role_systemd_resolved:
      hosts:
        daniel-pc:

    role_thermald:
      hosts:
        daniel-fusion15:

    role_tuxedo_control_center:
      hosts:
        daniel-fusion15:

    role_user:
      hosts:
        daniel-pc:

