---

kernel_args__local:
  - "pci=noaer"

kernel_args__sunshine:
  - "drm.edid_firmware=DP-4:edid/edid.bin"
  - "video=DP-4:1920x1080@60e"

kernel_args__amdgpu:
  - "amdgpu.ppfeaturemask=0xFFF7FFFF"

