---

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ bluetooth_packages }}"
    state: "present"
  become: true

- name: "Ensure service is in desired state"
  ansible.builtin.service:
    name: "{{ bluetooth_service_name }}"
    enabled: "{{ bluetooth_service_enabled }}"
    state: "{{ bluetooth_service_state }}"
  become: true

