---

mkinitcpio_modules: []
mkinitcpio_binaries: []
mkinitcpio_files: []
mkinitcpio_hooks:
  - base
  - systemd
  - autodetect
  - microcode
  - modconf
  - kms
  - keyboard
  - keymap
  - sd-vconsole
  - block
  - lvm2
  - filesystems
  - fsck

