---

all:
  hosts:
    daniel-fusion15:
    daniel-pc-manjaro:

  children:
    role_brave:
      hosts:
        daniel-fusion15:
        daniel-pc-manjaro:

    role_configfiles:
      hosts:
        daniel-fusion15:
        daniel-pc-manjaro:

    role_discord:
      hosts:
        daniel-fusion15:
        daniel-pc-manjaro:

    role_grub:
      hosts:
        daniel-fusion15:
        daniel-pc-manjaro:

    role_intel_undervolt:
      hosts:
        daniel-fusion15:
    
    role_ite8291:
      hosts:
        daniel-fusion15:
    
    role_mkinitcpio:
      hosts:
        daniel-fusion15:
        daniel-pc-manjaro:
    
    role_neovim:
      hosts:
        daniel-fusion15:
        daniel-pc-manjaro:
    
    role_nvidia:
      hosts:
        daniel-fusion15:
    
    role_packages:
      hosts:
        daniel-fusion15:
        daniel-pc-manjaro:
    
    role_sddm:
      hosts:
        daniel-fusion15:
        daniel-pc-manjaro:
    
    role_sunshine:
      hosts:
        daniel-pc-manjaro:
    
    role_system:
      hosts:
        daniel-fusion15:
        daniel-pc-manjaro:
    
    role_thermald:
      hosts:
        daniel-fusion15:
        daniel-pc-manjaro:
    
    role_thunderbird:
      hosts:
        daniel-fusion15:
        daniel-pc-manjaro:
    
    role_tuxedo_control_center:
      hosts:
        daniel-fusion15:
