---

__keepassxc_packages: "{{ keepassxc_packages if keepassxc_packages is defined else _keepassxc_packages }}"
__keepassxc_command: "{{ keepassxc_command if keepassxc_command is defined else _keepassxc_command }}"
__keepassxc_autostart: "{{ keepassxc_autostart if keepassxc_autostart is defined else _keepassxc_autostart }}"

