---

- name: "Include distro-specific variables"
  ansible.builtin.include_vars: "defaults/{{ ansible_facts.distribution }}.yml"

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ __keepassxc_packages }}"
    state: "present"
  become: true

- name: "Create user service directory"
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.config/systemd/user"
    state: "directory"

- name: "Create user service"
  ansible.builtin.template:
    src: "templates/keepassxc.service.j2"
    dest: "{{ ansible_facts.user_dir }}/.config/systemd/user/keepassxc.service"
  register: "reg_keepassxc_service"

- name: "Reload systemd daemon"
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: "user"
  when: "reg_keepassxc_service.changed is true"

- name: "Enable service"
  ansible.builtin.systemd_service:
    name: "keepassxc.service"
    scope: "user"
    enabled: true
  when: "__keepassxc_autostart is true"
