---

- name: "Set hostname"
  ansible.builtin.copy:
    dest: "/etc/hostname"
    content: |
      {{ inventory_hostname }}
  become: true

- name: "Configure locale"
  block:
    - name: "Configure /etc/locale.gen"
      ansible.builtin.blockinfile:
        path: "/etc/locale.gen"
        block: "{{ system_locale }}{{ ' ' ~ system_locale_charset if system_locale_charset is defined and (system_locale_charset | length > 0) else '' }}"
        prepend_newline: true
        append_newline: true
      become: true
      register: reg_system_locale

    - name: "Run locale-gen"
      ansible.builtin.command:
        cmd: "locale-gen"
      when: "reg_system_locale.changed | bool is true"

    - name: "Configure /etc/locale.conf"
      ansible.builtin.copy:
        dest: "/etc/locale.conf"
        content: |
          LANG={{ system_locale }}
      become: true

- name: "Configure timezone"
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ system_timezone }}"
    dest: "/etc/localtime"
    state: "link"
  become: true

- name: "Get timedatectl configuration"
  ansible.builtin.command:
    cmd: "timedatectl show"
  register: "reg_timedatectl"
  changed_when: false

- name: "Enable NTP"
  ansible.builtin.command:
    cmd: "timedatectl set-ntp 1"
  become: true
  when: "'NTP=no' in reg_timedatectl.stdout_lines"

- name: "Configure pacman"
  ansible.builtin.copy:
    src: "files/pacman.conf__{{ inventory_hostname }}"
    dest: "/etc/pacman.conf"
  become: true
  when: "(role_path ~ '/files/pacman.conf__' ~ inventory_hostname) is file"

