---

- name: "Include distro-specific variables"
  ansible.builtin.include_vars: "defaults/{{ ansible_distribution }}.yml"

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ _packages }}"
    state: "present"
  become: true
