---

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ discord_packages }}"
    state: "present"
  become: true

- name: "Create user service directory"
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.config/systemd/user"
    state: "directory"

- name: "Create user service"
  ansible.builtin.template:
    src: "templates/discord.service.j2"
    dest: "{{ ansible_facts.user_dir }}/.config/systemd/user/discord.service"
    mode: "0644"
  register: "reg_discord_service"

- name: "Reload systemd daemon"
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: "user"
  when: "reg_discord_service.changed is true"

- name: "Enable service"
  ansible.builtin.systemd_service:
    name: "discord.service"
    scope: "user"
    enabled: true
  when: "discord_autostart is true"
