---

- name: "Install packages"
  ansible.builtin.package:
    name:
      - "wget"
      - "jq"
    state: "present"
  become: true

- name: "Create script directory"
  ansible.builtin.file:
    path: "{{ discord_script_path | ansible.builtin.dirname }}"
    state: "directory"

- name: "Copy discord script"
  ansible.builtin.copy:
    src: "files/discord.sh"
    dest: "{{ discord_script_path }}"
    mode: "0700"

- name: "Create user service directory"
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.config/systemd/user"
    state: "directory"

- name: "Create user service"
  ansible.builtin.template:
    src: "templates/discord.service.j2"
    dest: "{{ ansible_facts.user_dir }}/.config/systemd/user/discord.service"
    mode: "0644"
  register: "reg_discord_service"

- name: "Reload systemd daemon"
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: "user"
  when: "reg_discord_service.changed is true"

- name: "Enable service"
  ansible.builtin.systemd_service:
    name: "discord.service"
    scope: "user"
    enabled: true
  when: "discord_autostart is true"
