---

- name: "Include distro-specific variables"
  ansible.builtin.include_vars: "defaults/{{ ansible_distribution }}.yml"

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ _packages }}"
    state: "present"
  become: true

- name: "Create config"
  ansible.builtin.template:
    src: "intel-undervolt.conf.j2"
    dest: "/etc/intel-undervolt.conf"
  become: true

- name: "Create service override"
  ansible.builtin.copy:
    src: "override.conf"
    dest: "/etc/systemd/system/intel-undervolt.service.d/override.conf"
  become: true

- name: "Enable service"
  ansible.builtin.service:
    name: "{{ intel_undervolt_service_name }}"
    enabled: "{{ intel_undervolt_service_enabled }}"
    state: "{{ intel_undervolt_service_state }}"
  become: true

