---

- name: "Include distro-specific variables"
  ansible.builtin.include_vars: "defaults/{{ ansible_distribution }}.yml"

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ _packages }}"
    state: "present"

- name: "Copy files"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  become: true
  loop:
    - src: "files/nvidia-pm.conf"
      dest: "/etc/modprobe.d/nvidia-pm.conf"
      owner: "root"
      group: "root"
      mode: "0644"
    - src: "files/plasmawayland-dgpu.desktop"
      dest: "/usr/share/wayland-sessions/plasmawayland-dgpu.desktop"
      owner: "root"
      group: "root"
      mode: "0644"
    - src: "files/plasmawayland-dgpu"
      dest: "/usr/local/bin/plasmawayland-dgpu"
      owner: "root"
      group: "root"
      mode: "0755"
    - src: "files/plasmawayland-igpu.desktop"
      dest: "/usr/share/wayland-sessions/plasmawayland-igpu.desktop"
      owner: "root"
      group: "root"
      mode: "0644"
    - src: "files/plasmawayland-igpu"
      dest: "/usr/local/bin/plasmawayland-igpu"
      owner: "root"
      group: "root"
      mode: "0755"
    - src: "files/gpuoff"
      dest: "/usr/local/bin/gpuoff"
      owner: "root"
      group: "root"
      mode: "0755"
