---

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ lact_packages }}"
    state: "present"
  become: true

- name: "Ensure service desired state"
  ansible.builtin.service:
    name: "{{ lact_service_name }}"
    enabled: "{{ lact_service_enabled }}"
    state: "{{ lact_service_state }}"
  become: true

- name: "Block: config"
  when: "lact_service_state != 'stopped'"
  block:
    - name: "Include GPU ID tasks"
      ansible.builtin.include_tasks: gpu_id.yml
      loop: "{{ lact_config_gpus }}"
      loop_control:
        loop_var: "current_gpu"

    - name: "Create config file"
      ansible.builtin.template:
        src: "config.yaml.j2"
        dest: "{{ lact_config_path }}/config.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      become: true
      notify: "Restart service"

