---

- name: "Include distro-specific variables"
  ansible.builtin.include_vars: "defaults/{{ ansible_facts.distribution }}.yml"
  when: "('defaults/' ~ ansible_facts.distribution ~ '.yml') is file"

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ _packages }}"
    state: "present"
  become: true

- name: "Ensure neovim config directory exists"
  ansible.builtin.file:
    path: "{{ neovim_config_dir }}"
    state: "directory"

- name: "Clone and update neovim config repository"
  ansible.builtin.git:
    repo: "{{ neovim_config_git }}"
    dest: "{{ neovim_config_dir }}"
    accept_newhostkey: true

- name: "Set Push URL"
  ansible.builtin.git_config:
    repo: "{{ neovim_config_dir }}"
    scope: "local"
    name: "remote.origin.pushurl"
    value: "{{ neovim_config_git_push }}"
